
import { GoogleGenAI } from "@google/genai";
import { RoomType, DesignStyle } from "../types";
import { compressImage } from "../utils";

function getClosestAspectRatio(width: number, height: number): string {
    if (!width || !height) return "1:1";
    const ratio = width / height;
    const choices = [
        { id: "1:1", val: 1.0 },
        { id: "3:4", val: 3/4 },
        { id: "4:3", val: 4/3 },
        { id: "9:16", val: 9/16 },
        { id: "16:9", val: 16/9 }
    ];
    return choices.reduce((prev, curr) => 
        Math.abs(curr.val - ratio) < Math.abs(prev.val - ratio) ? curr : prev
    ).id;
}

export async function generateRoomRedesign(
  base64Image: string,
  roomType: RoomType,
  style: DesignStyle,
  styleDescription: string = '',
  referenceImage?: string
): Promise<{ imageUrl: string; notes: string }> {
  
  // Initialize here to ensure we use the latest API key from the environment/dialog
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  // 1. Optimize Image (Resize if needed)
  const imgData = await compressImage(base64Image);
  const cleanBase64 = imgData.base64.split(',')[1];
  
  // Calculate aspect ratio to prevent cropping/zooming
  const aspectRatio = getClosestAspectRatio(imgData.width, imgData.height);

  let contentsPayload: any[] = [];
  let prompt = '';

  if (referenceImage) {
      // Logic for Multi-Angle / Consistency
      const refData = await compressImage(referenceImage);
      const refBase64 = refData.base64.split(',')[1];

      prompt = `
        You are an expert architectural visualizer.
        
        GOAL: Apply the design style from the 'Reference Design' to the 'Target Image' strictly preserving structure.
        Room Type: ${roomType}
        Target Style: ${style}
        
        INSTRUCTIONS:
        1. FREEZE CAMERA: The output must match the input image's viewpoint, angle, and field of view EXACTLY.
        2. STRUCTURE: Keep walls, windows, ceilings, and floors in their exact positions.
        3. REDESIGN: Change materials, furniture, and decor to match the reference.
        
        Action: "Reskin" the room.
      `;

      contentsPayload = [
        {
            inlineData: { mimeType: refData.mimeType, data: refBase64 }
        },
        {
            inlineData: { mimeType: imgData.mimeType, data: cleanBase64 }
        },
        { text: prompt }
      ];

  } else {
      // Logic for Initial Design
      prompt = `
        You are a professional interior design AI. 
        
        TASK: Renovate the room in this image to be a distinct "${style}" design.
        Room Type: ${roomType}
        Style Description: ${styleDescription}

        STRICT VISUAL CONSTRAINTS:
        1. CAMERA MATCH: The output MUST use the EXACT same camera angle, perspective, and zoom as the input. Do NOT crop.
        2. STRUCTURAL LOCK: Do not move walls, windows, doors, or ceiling beams.
        3. IN-PLACE REDESIGN: Replace furniture/decor in their current locations with "${style}" equivalents.
        
        STYLE DIRECTION:
        Make the "${style}" aesthetic obvious and profound. ${styleDescription}
        Use high-quality textures, lighting, and appropriate decor to sell the look.
        
        Output a photorealistic render.
      `;

      contentsPayload = [
        {
            inlineData: { mimeType: imgData.mimeType, data: cleanBase64 }
        },
        { text: prompt }
      ];
  }

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview', 
      contents: { parts: contentsPayload },
      config: {
          imageConfig: {
              aspectRatio: aspectRatio as any,
              imageSize: '1K'
          }
      }
    });

    let imageUrl = '';
    let textResponse = '';

    const parts = response.candidates?.[0]?.content?.parts;
    
    if (parts) {
      for (const part of parts) {
        if (part.inlineData) {
            imageUrl = `data:image/png;base64,${part.inlineData.data}`;
        } else if (part.text) {
            textResponse += part.text;
        }
      }
    }

    if (!imageUrl) {
        throw new Error("No image generated by the model. Please try a different photo or style.");
    }

    return { 
        imageUrl, 
        notes: textResponse.trim() 
    };

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
}
